mongodb/mongo-perf

testcases/simple_insert.js

Patch build here: https://evergreen.mongodb.com/version/5af213e8e3c33109e3ca2185

PERF-1454: Move Insert.LargeDocVector to be last in the task - again

---

testcases/pipeline_update.js
testcases/simple_commands.js

Three things to note right off the bat:
1. The tags will have to include some special 'pipeline-update' tag so that we can include them in their own task, which is the plan outlined in [this doc](https://docs.google.com/document/d/1Nrn3lxthZOgQYaABNB4qvpQA-YykXI2LtyxAw03yEBk/edit#)
2. Unlike that document, we didn't port over FindAndModifySortedRemoveIndexed. This was doing a remove-style findAndModify, so there's no pipeline-equivalent to write.
3. I forgot to give the last workload a new name so there's a duplicate name. Sorry! I'll propose a name inline in a comment or in the next patch.
[patch build](https://evergreen.mongodb.com/version/5ce5599ee3c33108d18855b2)
For some reason the new workloads aren't showing up in a way that's easy to find? They're in the logs though! Extracted …

PERF-1825 Add microbenchmarks for new pipeline-style findAndModify

---

testcases/pipeline_update.js

Fix the erroneous microbenchmark. I've run two evergreen patch builds for this new microbenchmark before and after generating $v:2 oplog entries. The regression now is within 1%.
est                                                                                          | 1          | 2        | 4          | 8          | Max
--                                                                                            | --        | --       | --         | --          | --
PipelineUpdate.IncFewLargeDocLongFields (Before v:2) | 4,803 | 9,463 | 16,434 | 18,523 | 18,523     
--                                                                                            | --        | --       | --         | --         | --        
PipelineUpdate.IncFewLargeDocLongFields (After v:2 and optimizing …

PERF-2028 IncFewLargeDocLongFields is measuring a query that fails

---

benchrun.py
gui/static/js/main.js
util/utils.js

Due to failures in [this perf patch](https://spruce.mongodb.com/version/60f992f41e2d174cc3663d1d/tasks), I'm deleting all logic relating to safe mode from the mongo-perf repo as well.

SERVER-58309 Delete logic surrounding the now-deprecated safe mode

---

testcases/pipelines.js

Evergreen: https://spruce.mongodb.com/version/6185699dc9ec4478d17aeea3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
(I ran this locally with the latest changes pulled in and it works)

Update syntax in perf tests for $minN/$maxN/$firstN/$lastN

---

testcases/pipelines.js

[evergreen run](https://spruce.mongodb.com/version/61800e9d61837d5ec679b2a8)
These accumulators are all very similar so I just have one parameterized test for all 4 of them. They are similar to minN/maxN but support having the output be a different value that what the documents are being sorted by.
I used some es6 JS stuff here and the build passed. I didn't see much es6 happening in this file, but if this is any issue I can refactor it to just use es5 JS.

PERF-2486 Add performance tests for $bottom/$top/$bottomN/$topN accumulators

---

testcases/pipelines.js

I manually checked the syntax using this command `echo -e 'load("util/utils.js"); load("util/docGenerators.js");\n' $(ls testcases/ | awk '{print "load(\"testcases/" $1 "\");"}') |  /path/to/mongo/for/version` with 4.0.27 and 3.6.23 shells downloaded from https://www.mongodb.com/try/download/community. The command just loads dependencies and then loads all of the files under testcases to make sure there is no syntax errors on loading.
[evergreen run](https://spruce.mongodb.com/version/61ca129d0305b92df5e4751e/tasks)
bizarrely Array's forEach method works fine in the 4.0 shell but `for (const var of [])` doesn't?

PERF-2741 make syntax in testcases/pipelines.js compatible with older shell versions

---

testcases/wildcard_index_query.js

I tested this locally and the error went away and it started reporting data. [here](https://spruce.mongodb.com/version/632206249ccd4e77c0d24dc7/tasks) is a patch build that will hopefully eventually finish. When I looked at the benchRun parser it had the option for specifying sort at the top level so I just used that instead.

PERF-3282 remove unsupported use of  in wildcard benchmarks

---

testcases/simple_query.js

[evergreen perf patch](https://spruce.mongodb.com/version/633b653aa4cf47053a6d24df/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (base)
[evergreen perf patch](https://spruce.mongodb.com/version/633b63d13627e075845e4368/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (with https://github.com/10gen/mongo/pull/7252)
variant | test | thread_level | measurement | value | value_base | percent_base_diff
-- | -- | -- | -- | -- | -- | --
SBE | Queries.RangeQuery_MultipleIndexes_LowSelectivityMatch_LL | 4 | ops_per_sec | 14.57 | 13.72 | 6.18%
SBE | Queries.RangeQuery_MultipleIndexes_LowSelectivityMatch_LL | 1 | ops_per_sec | 3.82 | 3.66 | 4.29%
Classic | Queries.RangeQuery_MultipleIndexes_LowSelectivityMatch_LL | 4 | ops_per_sec | 16.84 | 14.97 | 12.47%
Classic | …

PERF-3365 Extend index scan microbenchmarks

---

testcases/pipelines.js

See the comments on the ticket, especially [here](https://jira.mongodb.org/browse/PERF-3042?focusedCommentId=4915583&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4915583), for additional context.
I ran the queries locally and confirmed that they return apparently sensible results. I also ran the benchmarks locally through `benchrun.py` and got reasonable ops/sec numbers. Also kicked off a [patch build here](https://spruce.mongodb.com/version/635161180305b9742c217f39/tasks).

PERF-3042 Add $group benchmarks for aggregating into a single group

---

package-lock.json

The Project of `mongodb/mongo-perf` used lodash before 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep allows a malicious user to modify the prototype of Object via `{constructor: {prototype: {...}}}` causing the addition or modification of an existing property that will exist on all objects.
**PoCs By Defcon:**
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload. Following is an example of how this vulnerability will impact a JavaScript application:
```js
const mergeFn = require('lodash').defaultsDeep;
const payload = '{"constructor": {"prototype": {"a0": true}}}'
function check() {
mergeFn({}, JSON.parse(payload));
if (({})[`a0`] === true) {
console.log(`Vulnerable to Prototype Pollution …
```

SERVER-72240 Fixed Prototype Pollution in lodash

---

testcases/compound_wildcard_index_insert.js

Example results for `python benchrun.py -f testcases/compound_wildcard_index_insert.js  -t 1 2` run:
```
[CWI.insert] Compound Regular Index with 2 fields. Inserting batches of 1 doc.
1       6902.051443623284
2       13363.981237054299
[CWI.insert] Compound Regular Index with 2 fields. Inserting batches of 100 docs.
1       2834.467346848199
2       5171.561846858444
[CWI.insert] Compound Regular Index with 2 fields. Inserting batches of 1000 docs.
1       629.491045794724
2       1194.8517838129765
[CWI.insert] Compound Wildcard Index with 2 fields. Inserting batches of 1 doc.
1       7313.298467546089
2       13065.661304191573
[CWI.insert] Compound Wildcard Index with 2 fields. Inserting batches of 100 docs.
1       2772.96291187096
2       5249.832288417547
[CWI.insert] Compound …
```

PERF-3797 Add CWI intersection performance tests

---

testcases/compound_wildcard_index_query.js

Command to run:
```
python benchrun.py -f testcases/compound_wildcard_index_query.js --readCmd --trialTime 1 -t 4 8
```
Some of the test results (too many tests to list all of them):
```
[CWI.query] Regular. 3 fields. Point Query. Collection size 1000 docs.
4       11042.0704081908
8       17324.696637905443
[CWI.query] Regular. 3 fields. Point Query. With sort. Collection size 1000 docs.
4       7792.836108539934
8       9717.905928672071
[CWI.query] Regular. 3 fields. Point Query. Covered. Collection size 1000 docs.
4       11862.041666583367
8       17643.578329172222
[CWI.query] Regular. 3 fields. Point Query. Collection size 100000 docs.
4       11463.941764615327
8       17339.561328190208
[CWI.query] Regular. 3 fields. Point Query. With sort. Collection size 100000 docs.
4 …
```

PERF-3800 Add CWI.query tests

---

testcases/compound_wildcard_index_update.js

Command to run:
`python benchrun.py -f testcases/compound_wildcard_index_update.js  -t 1 2`
Results:
```
[CWI.update] Compound Regular Index with 2 fields. Collection size 1000 docs.
1	4385.137768761428
2	8622.722301184514
[CWI.update] Compound Regular Index with 2 fields. Collection size 100000 docs.
1	4466.134711598132
2	8503.479587049273
[CWI.update] Compound Wildcard Index with 2 fields. Collection size 1000 docs.
1	6008.4125375288295
2	11465.00381980137
[CWI.update] Compound Wildcard Index with 2 fields. Collection size 100000 docs.
1	5878.209546010708
2	11349.564424392234
[CWI.update] Compound Regular Index with 2 fields, one of which is multikey. Collection size 1000 docs.
1	5901.702554191269
2	11078.197346064375
[CWI.update] Compound Regular Index with 2 fields, one of which is …
```

PERF-3799 Add CWI.update tests

---

testcases/simple_query.js

I accidentally pushed this directly to master the first time... oops!! Reverted that and here's a PR.
**Jira Ticket:** PERF-4317
Added a 'fast_running_query' tag to a couple workloads we care about for PM-2885
[🌲 patch](https://spruce.mongodb.com/version/64931872850e61bfbc39556a/tasks)
**Related PRs:**
https://github.com/10gen/mongo/pull/13721

PERF-4317 Add fast running query tag

---

testcases/pipelines.js

**Jira Ticket:** SERVER-52958
Add more perf test for COUNT SCAN
[patch](https://spruce.mongodb.com/version/645dbca861837d14ab89e861/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=agg-query-comparison_read_commands)
**Workload Submission form:**
If applicable, only required if there is a new workload being added. Form can be found [here](https://docs.google.com/forms/d/1r0kOHvFUa7rJxVmX_wp9prxYU5K155yKyZ1y3d5yhZg/edit)
**Related PRs:**
https://github.com/10gen/mongo/pull/12502
https://github.com/10gen/mongo/pull/12629

SERVER-52958 Add more perf test for COUNT SCAN

---

testcases/tie_breaking.js

The test results in op/sec. with the tie breaking knob enabled and disabled. 
```
TieBreaking.Longest Index Prefix
8       513.8479528896214
Regular.Longest Index Prefix
8       44.694536921251505
TieBreaking.Equality
8       506.8080551614268
Regular.Equality
8       161.7573477034724
TieBreaking.Shortest Index
8       510.61094659644266
Regular.Shortest Index
8       429.83690121885473
TieBreaking.Shortest Index With Comparisons
8       241.43640952463656
Regular.Shortest Index With Comparisons
8       237.93900544287968
TieBreaking.Not Broken Tie
8       520.1677700619116
Regular.Not Broken Tie
8       501.3517774484123
TieBreaking.Multi Interval Index Bounds
8       1418.8523158938228
Regular.Multi Interval Index Bounds
8       589.0653669061361
TieBreaking.Non-Blocking Sort
8 …
```

SERVER-80273 Implement tie breaking performance tests

---

testcases/tie_breaking.js

`etc/system_perf.yml` requires tags for secondary filters

SERVER-80273 Add tags to tie breaking tests

---

testcases/tie_breaking.js

Two new benchmarks:
* one that demonstrates improvements given by taking into account closed intervals
* a case when the index prefix heuristics does not work well without CE
```
TieBreaking.Closed Interval
8       398.8404909247835
Regular.Closed Interval
8       211.81414242891609
TieBreaking.Failure: Longest Index Prefix
8       540.2319228208203
Regular.Failure: Longest Index Prefix
8       6537.653191254949
```

SERVER-80273 Add tie-breaking perf tests

---

testcases/simple_query.js

**Jira Ticket:** [PERF-4567](https://jira.mongodb.org/browse/PERF-4567)
Added a test case that excludes a large array to test that this field doesn't unnecessarily get loaded into the cache.
**Related PRs:**
Tests the change made in [SERVER-80157](https://github.com/10gen/mongo/pull/15969)
**Patch Build:** [Patch](https://spruce.mongodb.com/version/651b07893066151ab2c1fa67/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4567 Add a test case that excludes a large array

---

testcases/pipelines.js

**Jira Ticket:** PERF-4087
Added Lookup.UncorrelatedJoin.NoCache.LargeCollection and Lookup.UncorrelatedPrefixJoin.NoCache.LargeCollection perf tests. 
https://spruce.mongodb.com/version/6530faf7d1fe079737233a97/tasks

PERF-4087 Added appropriate dataset sizes for lookup with disabled cache

---

testcases/pipelines.js
util/docGenerators.js

Add a variant of the Aggregation.Group.MinAccTopField_LLR10 microbenchmark called Aggregation.Group.MinAccTopField_LLR10_10LargeFieldNames that gives a more realistic production-type query, where the new test case differs from the original by:
1. Extracts more top-level fields from the documents (11 instead of 2)
2. Fields have more realistic name lengths, including some that share prefixes
This is related to [BF-30318](https://jira.mongodb.org/browse/BF-30318) and its fix ticket [SERVER-82972](https://jira.mongodb.org/browse/SERVER-82972).

PERF-4977 Add MinAccTopField_LLR10 microbench variant w realistic fields

---

testcases/simple_in_queries.js

**Jira Ticket:** SERVER-84402
Extend $in benchmarks to also run against a collection on 1M documents.
https://evergreen.mongodb.com/patch/658c3c5f850e617aecca3ce4

SERVER-84402 Extend mongo-perf $in benchmarks for larger unindexed collection

---

testcases/simple_in_queries.js

**Jira Ticket:** SERVER-84724
Reduce collection size to stop mongo-perf $in benchmarks from timing out. `query_read_commands` is currently timing out on Bonsai variants due to this. Once the $in regressions are fixed, we can try increasing the size back to 1M docs.
[patch 1](https://spruce.mongodb.com/version/659e8d36a4cf477e674c89a8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch 2](https://spruce.mongodb.com/version/659e96a3850e617197690046/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch 3](https://spruce.mongodb.com/version/659e9698d6d80a84c0823661/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch 4](https://spruce.mongodb.com/version/659e96881e2d17778ef0f450/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-84724 Reduce collection size to stop mongo-perf $in benchmarks from timing out

---

testcases/simple_query.js

**Jira Ticket:** SERVER-84399
Extend existing projection tests to run with cardinalities
System failure patch (hit 6hr timed-out because the 1M cardinality is too big for COLLSCAN plan.): 
https://spruce.mongodb.com/version/659556f6306615d965b84f58/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SERVER-84399 Extend existing projection tests to run with cardinalities

---

testcases/simple_in_queries.js
testcases/simple_sort_queries.js

Patch: https://spruce.mongodb.com/version/65f372922e0d6600072011ba/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
8 minutes for the new suite vs 4 hours previously :)

SERVER-87587 Tag relevant "high value" cases for agg-query-comparison_read_commands suite

---

testcases/simple_query.js

**Jira Ticket:** SERVER-83288
Add a new perf test case for compound index with two integer fields, the existing ones are with random doubles so that there isn't range scanning for the same first fields.
**Related PRs:**
https://github.com/10gen/mongo/pull/19125

SERVER-83288 Add perf test case for compound index

---

benchrun.py
requirements.txt
util/utils.js

1. Includes median and stdev for each test result
2. Allows users to provide a variant name and list of variant values and comparing the perf with different variants.
3. Allow users to use regex for filtering test names
4. Prints a summary at the end of test.
https://spruce.mongodb.com/version/664bdf7ab3280b0007d8c421/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
New `--tsvSummary` option output looks like
```
name                     variant    thread_count    ops_per_sec(mean)    ops_per_sec(median)    count    stdev
---------------------  ---------  --------------  -------------------  ---------------------  -------  -------
Aggregation.Group.All          0               1            1628.9812              1627.5134        3   3.7440
Aggregation.Group.All          1               1 …
```

SERVER-90613 Zixuan Skunkworks 2024: Improve microbenchmark benchrun.py

---

testcases/compound_wildcard_index_insert.js

**Jira Ticket:** [SERVER-90103](https://github.com/mongodb/mongo-perf/commit/8b8c0fb7e1bbe52e76552b5d7d208f90f845f1c1)
This patch fixes a write workload of compound wildcard index. The workloads were inserting documents with duplicateKey error because the documents to insert were not changed in every batch insert. Remove the _id field in the generated documents to prevent the error.

SERVER-90103 Fix compound_wildcard_index_insert.js workload
